#!/bin/bash


export MKL_INC_DIR=$MKLROOT/include/intel64/lp64
export MKL_LIB_DIR=$MKLROOT/lib
thisrun="${PWD##*/}"

cd Build_Optim
make clean
make all &>../shell_output.txt
cd ..

bsub -R "rusage[mem=4096]" -W 100 -B -N -J $thisrun -o shell_output.txt "./Build_Optim/epss3_01b >>shell_output.txt 2>&1; tar -cjf results.tar.bz2 model_output model_input; scp results.tar.bz2 isildur@82.130.121.29:~/Tempdh/Brutus/$thisrun; ssh isildur@82.130.121.29 "cd ~/Tempdh/Brutus/$thisrun; tar -xjf results.tar.bz2; rm results.tar.bz2""

# tar -xjf ${thisrun}.tar.bz2

# calib_id = "${EPSSDIR%%/*}" # gets the name (without .txt) of the current calibration_file used

# ./Build_Optim/ calib_ep/STY2scaleIR02.txt >>shell_output.txt 2>&1
# ./Build_Optim/ calib_ep/STY2noir.txt >>shell_output.txt 2>&1
# ./Build_Optim/ calib_ep/STY-IR03.txt >>shell_output.txt 2>&1

# mv shell_output.txt ./model_output/shell_output.txt

# ssh dharenbe@frbw.grid.uni-mannheim.de "ssh isildur@makrowi7.vwl.uni-mannheim.de 'scp -r danielh@brutus.ethz.ch:~/$thisrun/model_output danielh@brutus.ethz.ch:~/$thisrun/model_input ~/Tempdh/cheops_output/$thisrun'"
