#!/bin/sh -l

# #PBS -q devel
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -l walltime=4:59:00
#PBS -A AG-Ludwig
#PBS -m e
#PBS -j oe
#PBS -o qsub_output.txt

echo `cat $PBS_NODEFILE`
export NCORES=`cat $PBS_NODEFILE | wc -l`
export NNODES=`uniq $PBS_NODEFILE | wc -l`

module load intel/12.1
module load mkl/10.3
module load matlab

cd $PBS_O_WORKDIR

# Start der Anwendung
export MKL_INC_DIR=$MKLINC/intel64/lp64
export MKL_LIB_DIR=$MKLLIB

cd Debug_IA-32
sed -i 's/-lmkl_lapack95 /-lmkl_lapack95_lp64 /g' objects.mk
make clean
make all &>../shell_output.txt
cd ..


./Debug_IA-32/epss2_17d >>shell_output.txt 2>&1

mv shell_output.txt ./model_output/shell_output.txt
