#!/bin/bash

# #BSUB-q pub.7d                    # Job queue 1h, 8h, 36h, 7d
#BSUB-W 36:00                         # Time limit in minutes (or HH:MM)
#BSUB-n 16            # number of processors / threads
# #BSUB-R "rusage[mem=4096]"          # Memory in MB per processor
# #BSUB-M 64000000                     # Memory requirements in Kbytes, not sure this works on Brutus
# #BSUB-R "select[model==Opteron8380]"   # Select CPU Type: OpteronXXXX: 2220 (ok), 8220, 8380 (best), 8384, 6174 (worst), XeonE7_8837 (excessive)
#BSUB-oo bsub_output.txt           # Redirect output to file
#BSUB-B                             # Send email when begins
#BSUB-N                             # Send email when ends

thisrun="${PWD##*/}"

lshosts -w $HOSTNAME >bsub_output.txt 2>&1
echo " "  >>bsub_output.txt 2>&1

cd $BUILD
make clean >>../bsub_output.txt 2>&1
make all >>../bsub_output.txt 2>&1
cd ..

if [[ "$BUILD" == *Debug* ]]; then
    gdb --batch --eval-command=run --eval-command=bt --nw --args ./$BUILD/epss4 >./model_output/shell_output.txt 2>&1
    # module load valgrind # use either gdb or valgrind
    # valgrind --error-limit=no  ./$BUILD/epss4 >>shell_output.txt 2>&1 # not tested
else
    ./$BUILD/epss4 >./model_output/shell_output.txt 2>&1
fi

# mv bsub_output.txt ./model_output/bsub_output.txt
tar -cjf results.tar.bz2 model_output model_input

scp results.tar.bz2 $USERNAME@$MY_IP:$path_to_results/$thisrun
ssh $USERNAME@$MY_IP "cd $path_to_results/$thisrun; tar -xjf results.tar.bz2; rm results.tar.bz2"
scp bsub_output.txt $USERNAME@$MY_IP:$path_to_results/$thisrun
