#!/bin/bash

# #BSUB-q pub.7d                    # Job queue 1h, 8h, 36h, 7d
#BSUB-W 36:00                         # Time limit in minutes (or HH:MM)
#BSUB-n 16            # number of processors / threads
# #BSUB-R "rusage[mem=4096]"          # Memory in MB per processor
# #BSUB-M 64000000                     # Memory requirements in Kbytes, not sure this works on Brutus
# #BSUB-R "select[model==Opteron8380]"   # Select CPU Type: OpteronXXXX: 2220 (ok), 8220, 8380 (best), 8384, 6174 (worst), XeonE7_8837 (excessive)
#BSUB-oo bsub_output.txt           # Redirect output to file
#BSUB-B                             # Send email when begins
#BSUB-N                             # Send email when ends

thisrun="${PWD##*/}"

lshosts -w $HOSTNAME >shell_output.txt 2>&1
echo " "  >>shell_output.txt 2>&1

cd $BUILD
make clean
make all >>../shell_output.txt 2>&1
cd ..

if [[ "$BUILD" == *Debug* ]]; then
    gdb --batch --eval-command=run --eval-command=bt --nw --args ./$BUILD/epss4 >>shell_output.txt 2>&1
else
    ./$BUILD/epss4 >>shell_output.txt 2>&1
fi

mv shell_output.txt ./model_output/shell_output.txt
tar -cjf results.tar.bz2 model_output model_input

scp results.tar.bz2 isildur@82.130.121.40:~/Tempdh/Brutus/$thisrun
ssh isildur@82.130.121.40 "cd ~/Tempdh/Brutus/$thisrun; tar -xjf results.tar.bz2; rm results.tar.bz2"


############################### Notes ################################
# Get the name (without .txt) of the current calibration_file used
# calib_id = "${EPSSDIR%%/*}" 
# Run multiple times with different calibration files as input
# ./$BUILD/ calib_ep/STY-IR03.txt >>shell_output.txt 2>&1
# ./$BUILD/ calib_ep/STY2noir.txt >>shell_output.txt 2>&1
####################### End of Job File ##############################