#!/bin/bash
#
#*******************************************************************************
# Copyright (c) 2010-2017 Daniel Harenberg - All rights reserved.
#*******************************************************************************

# #BSUB-q 24h                    # Job queue 4h, 24h, 120h
#BSUB-W 10:00                         # Time limit in minutes (or HH:MM)
#BSUB-n 24            # number of processors / threads
# #BSUB-R "select[nthreads==2]" # force hyperthreading
#BSUB-R "select[model==XeonE5_2680v3]"   # Euler II nodes
# #BSUB-R "rusage[mem=4096]"          # Memory in MB per processor
# #BSUB-M 64000000                     # Memory requirements in Kbytes, not sure this works on Brutus
#BSUB-oo bsub_output.txt           # Redirect BSUB output to file
#BSUB-B                             # Send email when begins
#BSUB-N                             # Send email when ends

module unload intel
module load intel/2017.0.098

PROJECT=epss4
export thisrun="${PWD##*/}"
# export OMP_NUM_THREADS=48

cd $BUILD
lshosts -w $HOSTNAME >make_output.txt 2>&1
echo " "  >>make_output.txt 2>&1

make clean >>make_output.txt 2>&1
make -j$OMP_NUM_THREADS all >>make_output.txt 2>&1
cd ..

if [[ "$BUILD" == *Debug* ]]; then
    gdb-ia --batch --eval-command=run --eval-command=bt --nw --args ./$BUILD/$PROJECT >./model_output/shell_output.txt 2>&1
    # if gdb-ia not available on Euler (because older Intel version), use gdb
    # module load valgrind # use either gdb or valgrind
    # valgrind --error-limit=no  ./$BUILD/$PROJECT >>shell_output.txt 2>&1 # not tested
else
    ./$BUILD/$PROJECT >./model_output/shell_output.txt 2>&1
fi

tar -cjf results.tar.bz2 model_output model_input $BUILD/*.optrpt $BUILD/*.txt $BUILD/*.mk $BUILD/makefile
scp results.tar.bz2 $USERNAME@$MY_IP:$path_to_results/$thisrun
ssh $USERNAME@$MY_IP "cd $path_to_results/$thisrun; tar -xjf results.tar.bz2; rm results.tar.bz2"
